namespace igaServer.Seed;

/// <summary>用户提供的蔬菜清单（79 条）；入库分类为 Vegetables。部分名称已按常见拼写修正（如 Lettuce、Cauliflower）。</summary>
public static class VegetableCatalogNames
{
    public static readonly string[] Names =
    [
        "Mushroom",
        "Capsicum Green",
        "Capsicum Yellow",
        "Garlic Peeled",
        "Garlic bagged",
        "Garlic Loose",
        "Potato Dirt",
        "Potato Red",
        "Potato White Large",
        "Potato White Small",
        "Pumpkin Butternut",
        "Pumpkin Grey",
        "Pumpkin Jap",
        "Onion Large",
        "Onion Red",
        "Onion Small",
        "Cucumber",
        "Tomato Truss",
        "Egg plant",
        "Bean round",
        "Tomato",
        "Tomato for Packing",
        "Cucumber Baby",
        "Tomato Roma",
        "Ginger",
        "Tomato Cherry",
        "Cucumber Telegraph",
        "Capsicum Red",
        "Zucchini",
        "Lettuce Baby Spinach",
        "Lettuce Mixed Salad",
        "Lettuce Rocket",
        "Potato sweet",
        "Carrot baby box",
        "Carrot Bagged",
        "Carrot Loose",
        "Celery",
        "Broccoli",
        "Lettuce",
        "Lettuce Cos",
        "Chinese cabbage",
        "Silverbeet Spinach",
        "Leek",
        "Corn",
        "Kale",
        "wombok baby cabbage",
        "Tomato Snack blue box",
        "Sugar Pea",
        "Chilli long green",
        "Chilli hot",
        "Chilli Thai",
        "Lettuce Baby Cos",
        "Mushroom Brown",
        "Mushroom Sliced",
        "Tomato Cherry Truss",
        "Brussels Sprouts",
        "Asparagus",
        "Okra",
        "Broccolini",
        "Brussel Sprouts",
        "Avocado",
        "Cabbage",
        "Eggs",
        "Bean Sprouts",
        "Corn Baby",
        "Lettuce Green Oak",
        "Echallot",
        "Potato peeled 5kg",
        "Cauliflower",
        "Parsley Aussie",
        "Basil",
        "Coriander",
        "Dill",
        "Mint",
        "Parsley",
        "Bok Choy",
        "Spinach English",
        "Shallot",
        "small tray",
    ];
}
